name: Make release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Clear unrelated files
        run: |
          rm -rf .github
          rm LICENSE

      - name: Get latest tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || true)
          latest_code=$(echo "$latest_tag" | sed -E 's/[^0-9]//g')
          echo "latest_tag=${latest_tag}-mod" >> $GITHUB_ENV
          echo "latest_code=$latest_code" >> $GITHUB_ENV

      - name: Prepare module.prop for upload
        run: |
          sed -i 's/versionName/${{ env.latest_tag }} (${{ github.run_number }})/' module.prop
          sed -i 's/versionNumber/${{ env.latest_code }}/' module.prop

      - name: Upload module
        uses: actions/upload-artifact@v4
        with:
          name: DebugAssistant-${{ env.latest_tag }}-${{ github.run_number }}
          path: "*"
